# 工作流名称
name: dev-deploy

# 触发条件：当master分支有推送时
on:
  push:
    branches:
      - master

# 定义的工作
jobs:
  # 测试工作
  test:
    name: Run Lint and Test
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repo
        uses: actions/checkout@v3

      # 设置Node环境
      - name: Setup Node
        uses: actions/setup-node@v3

      # 安装pnpm 
      - name: Install pnpm 
        run: npm install -g pnpm

      # 安装项目依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 运行测试
      - name: Run tests
        run: pnpm run test

  # 构建文档工作
  build:
    name: Build docs
    runs-on: ubuntu-latest
    needs: test  # 依赖于test工作完成

    steps:
      # 检出代码
      - name: Checkout repo
        uses: actions/checkout@v3

      # 设置Node环境
      - name: Setup Node
        uses: actions/setup-node@v3

      # 安装pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 安装项目依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: npm run docs:build

      # 上传构建好的文档作为工件
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./packages/docs/.vitepress/dist

  # 部署工作
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build  # 依赖于build工作完成
    steps:
      # 下载之前上传的文档工件
      - name: Download docs
        uses: actions/download-artifact@v3
        with:
          name: docs

      # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.FDESGINUI_TOKEN }}
          publish_dir: .
